---
- name: Set OCP Console logout redirect to Keycloak
  kubernetes.core.k8s:
    state: patched
    api_version: config.openshift.io/v1
    kind: Console
    name: cluster
    definition:
      spec:
        authentication:
          logoutRedirect: "{{ ocp4_workload_console_auth_config_logout_redirect | trim }}"
