---

- name: Blockinfile | {{ _asset.description }}
  become: "{{ _asset.become | default(omit) }}"
  become_user: "{{ _asset.become_user | default(omit) }}"
  ansible.builtin.blockinfile:
    append_newline: "{{ _asset.append_newline | default(omit) }}"
    attributes: "{{ _asset.attributes | default(omit) }}"
    backup: "{{ _asset.backup | default(omit) }}"
    block: "{{ _asset.block }}"
    blockdelimiters: "{{ _asset.blockdelimiters | default(omit) }}"
    blockquote: "{{ _asset.blockquote | default(omit) }}"
    create: "{{ _asset.create | default(omit) }}"
    group: "{{ _asset.group | default(omit) }}"
    insertafter: "{{ _asset.insertafter | default(omit) }}"
    insertbefore: "{{ _asset.insertbefore | default(omit) }}"
    marker: "{{ _asset.marker | default('# ANSIBLE MANAGED BLOCK') }}"
    marker_begin: "{{ _asset.marker_begin | default(omit) }}"
    marker_end: "{{ _asset.marker_end | default(omit) }}"
    mode: "{{ _asset.mode | default(omit) }}"
    owner: "{{ _asset.owner | default(omit) }}"
    path: "{{ _asset.path }}"
    prepend_newline: "{{ _asset.prepend_newline | default(omit) }}"
    selevel: "{{ _asset.selevel | default(omit) }}"
    serole: "{{ _asset.serole | default(omit) }}"
    setype: "{{ _asset.setype | default(omit) }}"
    seuser: "{{ _asset.seuser | default(omit) }}"
    state: "{{ _asset.state }}"
    unsafe_writes: "{{ _asset.unsafe_writes | default(omit) }}"
