---

- name: Remove files
  become: "{{ _asset.become | default(omit) }}"
  become_user: "{{ _asset.become_user | default(omit) }}"
  when: _asset.state == 'remove'
  ansible.builtin.file:
    path: "{{ _asset.path }}"
    state: absent

- name: Manage files
  become: "{{ _asset.become | default(omit) }}"
  become_user: "{{ _asset.become_user | default(omit) }}"
  when: _asset.state != 'remove'
  ansible.builtin.file:
    group: "{{ _asset.group | default(omit) }}"
    mode: "{{ _asset.mode | default(omit) }}"
    owner: "{{ _asset.owner | default(omit) }}"
    path: "{{ _asset.path | default(omit) }}"
    src: "{{ _asset.src | default(omit) }}"
    state: "{{ _asset.state | default(omit) }}"
