---

- name: Fetch files via url server
  become: "{{ _asset.become | default(omit) }}"
  become_user: "{{ _asset.become_user | default(omit) }}"
  ansible.builtin.get_url:
    url: "{{ _asset.src }}"
    dest: "{{ _asset.dest }}"
    url_username: "{{ _asset.url_username | default(omit) }}"
    url_password: "{{ _asset.url_password | default(omit) }}"
    force_basic_auth: true
    owner: "{{ _asset.owner | default(omit) }}"
    group: "{{ _asset.group | default(omit) }}"
    mode: "{{ _asset.mode | default(omit) }}"
