---

- name: Group | {{ _asset.description }}
  become: "{{ _asset.become | default(omit) }}"
  become_user: "{{ _asset.become_user | default(omit) }}"
  ansible.builtin.group:
    force: "{{ _asset.force | default(omit) }}"
    gid: "{{ _asset.gid | default(omit) }}"
    local: "{{ _asset.local | default(omit) }}"
    name: "{{ _asset.name | default(omit) }}"
    non_unique: "{{ _asset.non_unique | default(omit) }}"
    state: "{{ _asset.state | default(omit) }}"
    system: "{{ _asset.system | default(omit) }}"
