---
- name: Lineinfile | {{ _asset.description }}
  become: "{{ _asset.become | default(omit) }}"
  become_user: "{{ _asset.become_user | default(omit) }}"
  ansible.builtin.lineinfile:
    attributes: "{{ _asset.attributes | default(omit) }}"
    backrefs: "{{ _asset.backrefs | default(omit) }}"
    backup: "{{ _asset.backup | default(omit) }}"
    create: "{{ _asset.create | default(omit) }}"
    firstmatch: "{{ _asset.firstmatch | default(omit) }}"
    group: "{{ _asset.group | default(omit) }}"
    insertafter: "{{ _asset.insertafter | default(omit) }}"
    insertbefore: "{{ _asset.insertbefore | default(omit) }}"
    line: "{{ _asset.line | default(omit) }}"
    mode: "{{ _asset.mode | default(omit) }}"
    owner: "{{ _asset.owner | default(omit) }}"
    path: "{{ _asset.path | default(omit) }}"
    regexp: "{{ _asset.regexp | default(omit) }}"
    search_string: "{{ _asset.search_string | default(omit) }}"
    serole: "{{ _asset.serole | default(omit) }}"
    seuser: "{{ _asset.seuser | default(omit) }}"
    state: "{{ _asset.state | default(omit) }}"
    unsafe_writes: "{{ _asset.unsafe_writes | default(omit) }}"
    validate: "{{ _asset.validate | default(omit) }}"
