---

- name: Template | {{ _asset.description }}
  become: "{{ _asset.become | default(omit) }}"
  become_user: "{{ _asset.become_user | default(omit) }}"
  ansible.builtin.template:
    src: "{{ _asset.src }}"
    dest: "{{ _asset.dest }}"
    owner: "{{ _asset.owner | default(omit) }}"
    group: "{{ _asset.group | default(omit) }}"
    mode: "{{ _asset.mode | default(omit) }}"
