---
- name: Unarchive | {{ _asset.description }}
  become: "{{ _asset.become | default(omit) }}"
  become_user: "{{ _asset.become_user | default(omit) }}"
  ansible.builtin.unarchive:
    src: "{{ _asset.src }}"
    dest: "{{ _asset.dest }}"
    remote_src: "{{ _asset.remote_src | default(omit) }}"
