---
galaxy_info:
  author: Mitesh Sharma <mitsharm@redhat.com>
  description: Install and configure Open Policy Agent (OPA) with systemd
  company: Red Hat
  license: Apache-2.0
  min_ansible_version: "2.9"
  platforms:
    - name: EL
      versions:
        - "8"
        - "9"
  galaxy_tags:
    - opa
    - policy
    - authorization
    - security
    - systemd

dependencies: []
